AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A trigger that will tell Dockstore to update all workflows associated with a
  GitHub repo and tag
Resources:
  upsertGitHubTag:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        A trigger that will tell Dockstore to update all workflows associated
        with a GitHub repo and tag
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::312767926603:role/serverlessrepo-cloudwatch-cloudwatchalarmtoslackRo-1MWUBBKPY1IYG
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 1
      Environment:
        Variables:
          DOCKSTORE_TOKEN: <fill me in>
          SECRET_TOKEN: <fill me in>
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
