version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        parameters:
            aws_bucket:
                type: string
                default: "${AWS_BUCKET}"
        steps:
            - when:
                condition: <<parameters.aws_bucket>>
                steps:
                    - checkout
                    - run:
                        name: Create deployment zip
                        command: zip upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/function.zip upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js
                        when: always
                    - aws-s3/copy:
                        from: upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/function.zip
                        to: 's3://${AWS_BUCKET}/$(echo ${CIRCLE_TAG-$CIRCLE_BRANCH} | sed "s/\//_/g")-$(echo $CIRCLE_SHA1 | cut -c -7)/handleGitHubPushEvent/function.zip'
                        arguments: |
                            --cache-control max-age=0