AWSTemplateFormatVersion: '2010-09-09'
Description: An Amazon SNS trigger that sends CloudWatch alarm notifications to Slack.
Parameters:
  KeyIdParameter:
    Type: String
  kmsEncryptedHookUrlParameter:
    Type: String
  slackChannelParameter:
    Type: String
Resources:
  SNSTopic1:
    Type: AWS::SNS::Topic
  cloudwatchalarmtoslack:
    Properties:
      CodeUri: s3://aws-sar-publishing/376e2767f8cf796f8f7a36e41cb5ae7e
      Description: An Amazon SNS trigger that sends CloudWatch alarm notifications
        to Slack.
      Environment:
        Variables:
          kmsEncryptedHookUrl: kmsEncryptedHookUrlParameter
          slackChannel: slackChannelParameter
      Events:
        SNS1:
          Properties:
            Topic:
              Ref: SNSTopic1
          Type: SNS
      Handler: index.handler
      MemorySize: 128
      Policies:
      - KMSDecryptPolicy:
          KeyId:
            Ref: KeyIdParameter
      Runtime: nodejs8.10
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
