# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Node.js CI with SAM

on: [push, pull_request]
jobs:
  linterWithESLint:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
       with:
         node-version: 12.x
     - run: npm install
     - run: npm run lint
  testWithSAMCLI:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install aws-sam-cli
     - name: Test with SAM CLI
       working-directory: ./upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7
       run: |
         sam local invoke HelloWorldFunction -e events/event.json -n env.json &> output.txt
         grep "Valid push event" output.txt
     - name: Test wdl parsing with SAM CLI build and invoke
       working-directory: ./wdl-parsing
       run: |
         sam build --use-container
         sam local invoke WDLParsingFunction -e events/event.json &> output.txt
         grep "statusCode\":200" output.txt
     - name: Run snyk on WDLParsingFunction
       working-directory: ./wdl-parsing
       uses: snyk/actions/maven-3-jdk-11@master
         continue-on-error: true # To make sure that SARIF upload gets called
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           args: --file=WDLParsingFunction/pom.xml --sarif-file-output=snyk.sarif



